from __future__ import annotations

import logging

from backend.database import Database

_log = logging.getLogger(__name__)


async def _table_exists(db: Database, table: str) -> bool:
    row = await db.fetch_one(
        "SELECT 1 FROM user_tables WHERE table_name = :table_name",
        {"table_name": table.upper()},
    )
    return row is not None


async def ensure_account_updates_schema(db: Database) -> None:
    """Create account updates table for per-account agent announcements."""
    if await _table_exists(db, "AIVA_ACCOUNT_UPDATES"):
        return

    await db.execute(
        """
        CREATE TABLE AIVA_account_updates (
            id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            account_id  NUMBER NOT NULL,
            title       VARCHAR2(500) NOT NULL,
            body        CLOB NOT NULL,
            is_active   NUMBER(1) DEFAULT 1 NOT NULL,
            created_by  NUMBER NOT NULL,
            created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at  TIMESTAMP,
            CONSTRAINT fk_aiva_account_updates_account
                FOREIGN KEY (account_id) REFERENCES AIVA_accounts(id),
            CONSTRAINT fk_aiva_account_updates_user
                FOREIGN KEY (created_by) REFERENCES AIVA_users(id)
        )
        """
    )
    await db.execute(
        "CREATE INDEX idx_aiva_account_updates_lookup ON AIVA_account_updates (account_id, is_active)"
    )
    _log.info("Created AIVA_account_updates table")
