from __future__ import annotations

import logging

from backend.database import Database

_log = logging.getLogger(__name__)


async def _table_exists(db: Database, table: str) -> bool:
    row = await db.fetch_one(
        "SELECT 1 FROM user_tables WHERE table_name = :table_name",
        {"table_name": table.upper()},
    )
    return row is not None


async def _column_exists(db: Database, table: str, column: str) -> bool:
    row = await db.fetch_one(
        """
        SELECT 1 FROM user_tab_cols
        WHERE table_name = :table_name AND column_name = :column_name
        """,
        {"table_name": table.upper(), "column_name": column.upper()},
    )
    return row is not None


async def ensure_audit_schema(db: Database) -> None:
    if not await _table_exists(db, "AIVA_AUDIT_LOGS"):
        await db.execute(
            """
            CREATE TABLE AIVA_audit_logs (
                id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id      NUMBER,
                entity_type  VARCHAR2(64) NOT NULL,
                entity_id    VARCHAR2(64) NOT NULL,
                action_type  VARCHAR2(64) NOT NULL,
                old_value    CLOB,
                new_value    CLOB,
                ip_address   VARCHAR2(64),
                created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
            )
            """
        )
        await db.execute(
            "CREATE INDEX idx_aiva_audit_created ON AIVA_audit_logs (created_at DESC)"
        )
        await db.execute(
            "CREATE INDEX idx_aiva_audit_user ON AIVA_audit_logs (user_id, created_at DESC)"
        )
        _log.info("Created AIVA_audit_logs table")
        return

    if not await _column_exists(db, "AIVA_AUDIT_LOGS", "created_at"):
        await db.execute(
            "ALTER TABLE AIVA_audit_logs ADD (created_at TIMESTAMP DEFAULT SYSTIMESTAMP)"
        )
        _log.info("Added AIVA_audit_logs.created_at column")
