from __future__ import annotations

import logging

from backend.database import Database

_log = logging.getLogger(__name__)


async def _column_exists(db: Database, table: str, column: str) -> bool:
    row = await db.fetch_one(
        """
        SELECT 1 FROM user_tab_cols
        WHERE table_name = :table_name AND column_name = :column_name
        """,
        {"table_name": table.upper(), "column_name": column.upper()},
    )
    return row is not None


async def _table_exists(db: Database, table: str) -> bool:
    row = await db.fetch_one(
        "SELECT 1 FROM user_tables WHERE table_name = :table_name",
        {"table_name": table.upper()},
    )
    return row is not None


async def ensure_auth_schema(db: Database) -> None:
    """Add auth-flow tables and columns for SMTP OTP sign-up and password reset."""
    user_columns = [
        ("email_verified_at", "TIMESTAMP"),
        ("failed_login_attempts", "NUMBER DEFAULT 0 NOT NULL"),
        ("locked_until", "TIMESTAMP"),
        ("otp_failed_attempts", "NUMBER DEFAULT 0 NOT NULL"),
        ("otp_locked_until", "TIMESTAMP"),
    ]
    for col_name, col_type in user_columns:
        if not await _column_exists(db, "AIVA_USERS", col_name):
            await db.execute(f"ALTER TABLE AIVA_users ADD ({col_name} {col_type})")
            _log.info("Added AIVA_users.%s", col_name)

    if not await _table_exists(db, "AIVA_EMAIL_OTPS"):
        await db.execute(
            """
            CREATE TABLE AIVA_email_otps (
                id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id          NUMBER NOT NULL,
                purpose          VARCHAR2(50) NOT NULL,
                otp_hash         VARCHAR2(255) NOT NULL,
                expires_at       TIMESTAMP NOT NULL,
                used_at          TIMESTAMP,
                failed_attempts  NUMBER DEFAULT 0 NOT NULL,
                resend_count     NUMBER DEFAULT 0 NOT NULL,
                last_sent_at     TIMESTAMP,
                created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT fk_aiva_email_otps_user
                    FOREIGN KEY (user_id) REFERENCES AIVA_users(id)
            )
            """
        )
        await db.execute(
            "CREATE INDEX idx_aiva_email_otps_lookup ON AIVA_email_otps (user_id, purpose, used_at)"
        )
        await db.execute(
            "CREATE INDEX idx_aiva_email_otps_expires ON AIVA_email_otps (expires_at)"
        )
        _log.info("Created AIVA_email_otps table")

    if not await _table_exists(db, "AIVA_AUTH_AUDIT_LOGS"):
        await db.execute(
            """
            CREATE TABLE AIVA_auth_audit_logs (
                id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id     NUMBER,
                event_type  VARCHAR2(100) NOT NULL,
                ip_address  VARCHAR2(100),
                user_agent  CLOB,
                metadata    CLOB,
                created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
            )
            """
        )
        _log.info("Created AIVA_auth_audit_logs table")
