"""Server-side error capture with full stack traces for the Errors & Failures view.

Rows are written best-effort from the request middleware when an unhandled
exception bubbles out of a handler (HTTP 500s). Reads are org-scoped like the
other log endpoints.
"""

from __future__ import annotations

import logging
from typing import Any

from backend.database import Database

_log = logging.getLogger(__name__)


async def _table_exists(db: Database, table: str) -> bool:
    row = await db.fetch_one(
        "SELECT 1 FROM user_tables WHERE table_name = :table_name",
        {"table_name": table.upper()},
    )
    return row is not None


async def ensure_error_log_schema(db: Database) -> None:
    if await _table_exists(db, "AIVA_ERROR_LOGS"):
        return
    await db.execute(
        """
        CREATE TABLE AIVA_error_logs (
            id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
            exception_type    VARCHAR2(255),
            exception_message VARCHAR2(2000),
            stack_trace       CLOB,
            source            VARCHAR2(16),
            http_method       VARCHAR2(10),
            path              VARCHAR2(512),
            route_template    VARCHAR2(512),
            status_code       NUMBER,
            request_id        VARCHAR2(64),
            user_id           NUMBER,
            user_email        VARCHAR2(255),
            org_id            NUMBER,
            client_ip         VARCHAR2(64)
        )
        """
    )
    await db.execute("CREATE INDEX idx_aiva_error_logs_created ON AIVA_error_logs (created_at DESC)")
    await db.execute("CREATE INDEX idx_aiva_error_logs_type ON AIVA_error_logs (exception_type)")
    await db.execute("CREATE INDEX idx_aiva_error_logs_org ON AIVA_error_logs (org_id, created_at DESC)")
    _log.info("Created AIVA_error_logs table")


async def persist_error_log(
    db: Database | None,
    *,
    exception_type: str,
    exception_message: str | None,
    stack_trace: str | None,
    source: str = "HTTP",
    http_method: str | None = None,
    path: str | None = None,
    route_template: str | None = None,
    status_code: int | None = None,
    request_id: str | None = None,
    user_id: int | None = None,
    user_email: str | None = None,
    org_id: int | None = None,
    client_ip: str | None = None,
) -> None:
    """Write one error record. Never raises to the caller."""
    if db is None:
        return
    try:
        await db.execute(
            """
            INSERT INTO AIVA_error_logs (
                exception_type, exception_message, stack_trace, source, http_method,
                path, route_template, status_code, request_id, user_id, user_email,
                org_id, client_ip
            ) VALUES (
                :exception_type, :exception_message, :stack_trace, :source, :http_method,
                :path, :route_template, :status_code, :request_id, :user_id, :user_email,
                :org_id, :client_ip
            )
            """,
            {
                "exception_type": (exception_type or "Error")[:255],
                "exception_message": (exception_message or "")[:2000] or None,
                "stack_trace": stack_trace or None,
                "source": (source or "HTTP")[:16],
                "http_method": (http_method or "")[:10] or None,
                "path": (path or "")[:512] or None,
                "route_template": (route_template or "")[:512] or None,
                "status_code": status_code,
                "request_id": (request_id or "")[:64] or None,
                "user_id": user_id,
                "user_email": (user_email or "")[:255] or None,
                "org_id": org_id,
                "client_ip": (client_ip or "")[:64] or None,
            },
        )
    except Exception:
        _log.warning("Failed to persist error log", exc_info=True)


def _error_filters(
    *, org_id: int | None, exception_type: str | None, start: str | None, end: str | None
) -> tuple[list[str], dict[str, Any]]:
    binds: dict[str, Any] = {}
    filters = ["1=1"]
    if org_id is not None:
        filters.append("(org_id = :org_id OR org_id IS NULL)")
        binds["org_id"] = org_id
    if exception_type:
        filters.append("exception_type = :exception_type")
        binds["exception_type"] = exception_type
    if start:
        filters.append("created_at >= TO_TIMESTAMP(:start_date, 'YYYY-MM-DD')")
        binds["start_date"] = start
    if end:
        filters.append("created_at < TO_TIMESTAMP(:end_date, 'YYYY-MM-DD') + 1")
        binds["end_date"] = end
    return filters, binds


async def list_error_logs(
    db: Database,
    *,
    org_id: int | None = None,
    exception_type: str | None = None,
    start: str | None = None,
    end: str | None = None,
    limit: int = 100,
    offset: int = 0,
) -> list[dict[str, Any]]:
    limit = max(1, min(limit, 500))
    offset = max(0, offset)
    filters, binds = _error_filters(org_id=org_id, exception_type=exception_type, start=start, end=end)
    binds.update({"limit": limit, "offset": offset})
    where_sql = " AND ".join(filters)
    rows = await db.fetch_all(
        f"""
        SELECT id, created_at, exception_type, exception_message, stack_trace, source,
               http_method, path, route_template, status_code, request_id, user_id,
               user_email, org_id, client_ip
        FROM AIVA_error_logs
        WHERE {where_sql}
        ORDER BY created_at DESC, id DESC
        OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
        """,
        binds,
    )
    return rows


async def error_type_counts(
    db: Database,
    *,
    org_id: int | None = None,
    start: str | None = None,
    end: str | None = None,
) -> list[dict[str, Any]]:
    filters, binds = _error_filters(org_id=org_id, exception_type=None, start=start, end=end)
    where_sql = " AND ".join(filters)
    rows = await db.fetch_all(
        f"""
        SELECT exception_type, COUNT(*) AS cnt
        FROM AIVA_error_logs
        WHERE {where_sql}
        GROUP BY exception_type
        ORDER BY COUNT(*) DESC
        """,
        binds,
    )
    return [{"exception_type": str(r.get("exception_type") or "Error"), "count": int(r.get("cnt") or 0)} for r in rows]
