from __future__ import annotations

import logging

from backend.database import Database

_log = logging.getLogger(__name__)


async def _table_exists(db: Database, table: str) -> bool:
    row = await db.fetch_one(
        "SELECT 1 FROM user_tables WHERE table_name = :table_name",
        {"table_name": table.upper()},
    )
    return row is not None


async def ensure_http_request_log_schema(db: Database) -> None:
    """Store explainable HTTP access logs for admin UI."""
    if await _table_exists(db, "AIVA_HTTP_REQUEST_LOGS"):
        return

    await db.execute(
        """
        CREATE TABLE AIVA_http_request_logs (
            id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
            http_method     VARCHAR2(10) NOT NULL,
            path            VARCHAR2(512) NOT NULL,
            query_string    VARCHAR2(1024),
            handler_name    VARCHAR2(128),
            route_template  VARCHAR2(512),
            status_code     NUMBER NOT NULL,
            duration_ms     NUMBER NOT NULL,
            user_id         NUMBER,
            user_email      VARCHAR2(255),
            org_id          NUMBER,
            user_roles      VARCHAR2(512),
            actor_label     VARCHAR2(512),
            client_ip       VARCHAR2(64)
        )
        """
    )
    await db.execute(
        "CREATE INDEX idx_aiva_http_logs_created ON AIVA_http_request_logs (created_at DESC)"
    )
    await db.execute(
        "CREATE INDEX idx_aiva_http_logs_org ON AIVA_http_request_logs (org_id, created_at DESC)"
    )
    _log.info("Created AIVA_http_request_logs table")
