from __future__ import annotations

import logging

from backend.database import Database

_log = logging.getLogger(__name__)


async def _table_exists(db: Database, table: str) -> bool:
    row = await db.fetch_one(
        "SELECT 1 FROM user_tables WHERE table_name = :table_name",
        {"table_name": table.upper()},
    )
    return row is not None


async def _column_exists(db: Database, table: str, column: str) -> bool:
    row = await db.fetch_one(
        """
        SELECT 1 FROM user_tab_cols
        WHERE table_name = :table_name AND column_name = :column_name
        """,
        {"table_name": table.upper(), "column_name": column.upper()},
    )
    return row is not None


async def ensure_rag_retrieval_schema(db: Database) -> None:
    """Store RAG retrieval traces so admins can diagnose bad AI answers."""
    if not await _table_exists(db, "AIVA_RAG_RETRIEVALS"):
        await db.execute(
            """
            CREATE TABLE AIVA_rag_retrievals (
                id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                session_id       NUMBER,
                account_id       NUMBER,
                corpus_id        VARCHAR2(128),
                query_text       CLOB,
                top_k            NUMBER,
                verticals        VARCHAR2(512),
                status           VARCHAR2(16) NOT NULL,
                chunks_returned  NUMBER DEFAULT 0 NOT NULL,
                top_score        NUMBER,
                retrieval_ms     NUMBER,
                error_message    VARCHAR2(2000),
                chunks_json      CLOB,
                source           VARCHAR2(16)
            )
            """
        )
        await db.execute(
            "CREATE INDEX idx_aiva_rag_created ON AIVA_rag_retrievals (created_at DESC)"
        )
        await db.execute(
            "CREATE INDEX idx_aiva_rag_account ON AIVA_rag_retrievals (account_id, created_at DESC)"
        )
        await db.execute(
            "CREATE INDEX idx_aiva_rag_session ON AIVA_rag_retrievals (session_id)"
        )
        _log.info("Created AIVA_rag_retrievals table")
        return

    # Table already exists (earlier deploy) — add the source column if missing.
    if not await _column_exists(db, "AIVA_RAG_RETRIEVALS", "source"):
        await db.execute("ALTER TABLE AIVA_rag_retrievals ADD (source VARCHAR2(16))")
        _log.info("Added AIVA_rag_retrievals.source column")
