"""Schema for the widget installer (.exe) release metadata.

Latest-only: at most one logical current release. The binary itself is stored on disk
(see widget_release.py / settings.widget_release_dir); this table keeps the version,
filename, size, uploader and timestamp for display and download naming.
"""

from __future__ import annotations

import logging

from backend.database import Database

_log = logging.getLogger(__name__)


async def _table_exists(db: Database, table: str) -> bool:
    row = await db.fetch_one(
        "SELECT 1 FROM user_tables WHERE table_name = :table_name",
        {"table_name": table.upper()},
    )
    return row is not None


async def ensure_widget_release_schema(db: Database) -> None:
    if await _table_exists(db, "AIVA_WIDGET_RELEASE"):
        return
    await db.execute(
        """
        CREATE TABLE AIVA_widget_release (
            id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            version           VARCHAR2(100) NOT NULL,
            original_filename VARCHAR2(400) NOT NULL,
            stored_filename   VARCHAR2(400) NOT NULL,
            file_size         NUMBER NOT NULL,
            content_type      VARCHAR2(200),
            notes             CLOB,
            uploaded_by       NUMBER NOT NULL,
            uploaded_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
        """
    )
    _log.info("Created AIVA_widget_release")
