"""Role name constants (shared; no imports from deps to avoid cycles)."""

ROLE_SUPER_ADMIN = "SUPER_ADMIN"
ROLE_ORG_ADMIN = "ORGANIZATION_ADMIN"
ROLE_ACCOUNT_MANAGER = "ACCOUNT_MANAGER"
ROLE_SUPERVISOR = "SUPERVISOR"
ROLE_AGENT = "AGENT"
ROLE_DEVELOPER = "DEVELOPER"
