STATUS_PENDING_EMAIL_VERIFICATION = "PENDING_EMAIL_VERIFICATION"
STATUS_ACTIVE = "ACTIVE"
STATUS_DISABLED = "DISABLED"
STATUS_PASSWORD_RESET_REQUIRED = "PASSWORD_RESET_REQUIRED"

OTP_PURPOSE_SIGNUP = "signup_verification"
OTP_PURPOSE_FORGOT_PASSWORD = "forgot_password"
