-- Document intelligence — migration V001 (Phase 1: knowledge-document import + monitoring)
--
-- Creates NEW, isolated tables only. No existing table is altered, and there are no
-- foreign keys to existing tables (account/org/user deletion flows stay untouched).
-- Apply with:   python -m backend.doc_intel.migrate apply --version 001 --confirm-schema <SCHEMA> --yes
-- Roll back:    python -m backend.doc_intel.migrate rollback --version 001 --confirm-schema <SCHEMA> --yes
-- All timestamps are UTC.

-- Applied-version ledger for this module's migrations.
CREATE TABLE AIVA_di_schema_version (
    version      VARCHAR2(16)  NOT NULL,
    description  VARCHAR2(256),
    checksum     VARCHAR2(64),
    applied_by   VARCHAR2(128),
    applied_at   TIMESTAMP(6)  DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    CONSTRAINT pk_aiva_di_schema_version PRIMARY KEY (version)
);

-- One row per uploaded knowledge document (also the import work queue).
CREATE TABLE AIVA_kb_documents (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY,
    batch_id           VARCHAR2(32),
    account_id         NUMBER        NOT NULL,
    corpus_id          VARCHAR2(32)  NOT NULL,
    queue_keys         CLOB,
    vertical           VARCHAR2(64),
    filename           VARCHAR2(1024) NOT NULL,
    content_type       VARCHAR2(128),
    size_bytes         NUMBER,
    sha256             VARCHAR2(64),
    storage_dir        VARCHAR2(1024),
    status             VARCHAR2(16)  DEFAULT 'QUEUED'  NOT NULL,
    upload_status      VARCHAR2(16)  DEFAULT 'PENDING' NOT NULL,
    extraction_status  VARCHAR2(16)  DEFAULT 'PENDING' NOT NULL,
    chunking_status    VARCHAR2(16)  DEFAULT 'PENDING' NOT NULL,
    embedding_status   VARCHAR2(16)  DEFAULT 'PENDING' NOT NULL,
    publishing_status  VARCHAR2(16)  DEFAULT 'PENDING' NOT NULL,
    failed_stage       VARCHAR2(16),
    error_message      VARCHAR2(4000),
    stage_details      CLOB,
    warnings_json      CLOB,
    page_count         NUMBER,
    chunk_count        NUMBER,
    tokens_used        NUMBER,
    cost_usd           NUMBER,
    attempts           NUMBER        DEFAULT 0 NOT NULL,
    worker_id          VARCHAR2(128),
    uploaded_by        NUMBER,
    created_at         TIMESTAMP(6)  DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    updated_at         TIMESTAMP(6)  DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    started_at         TIMESTAMP(6),
    finished_at        TIMESTAMP(6),
    published_at       TIMESTAMP(6),
    CONSTRAINT pk_aiva_kb_documents PRIMARY KEY (id),
    CONSTRAINT ck_aiva_kbdoc_status CHECK (status IN ('QUEUED', 'PROCESSING', 'PUBLISHED', 'FAILED', 'UNPUBLISHED')),
    CONSTRAINT ck_aiva_kbdoc_stages CHECK (
        upload_status     IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED') AND
        extraction_status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED') AND
        chunking_status   IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED') AND
        embedding_status  IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED') AND
        publishing_status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED')
    )
);

CREATE INDEX idx_aiva_kbdoc_account ON AIVA_kb_documents (account_id, created_at);

CREATE INDEX idx_aiva_kbdoc_status ON AIVA_kb_documents (status, created_at);

CREATE INDEX idx_aiva_kbdoc_sha ON AIVA_kb_documents (corpus_id, sha256);

-- Latest state per monitored component.
CREATE TABLE AIVA_health_checks (
    component_key         VARCHAR2(64)  NOT NULL,
    label                 VARCHAR2(128),
    status                VARCHAR2(16)  NOT NULL,
    reason                VARCHAR2(4000),
    suggested_action      VARCHAR2(2000),
    details_json          CLOB,
    latency_ms            NUMBER,
    checked_at            TIMESTAMP(6)  NOT NULL,
    last_success_at       TIMESTAMP(6),
    last_failure_at       TIMESTAMP(6),
    consecutive_failures  NUMBER        DEFAULT 0 NOT NULL,
    CONSTRAINT pk_aiva_health_checks PRIMARY KEY (component_key),
    CONSTRAINT ck_aiva_health_status CHECK (status IN ('HEALTHY', 'FAILED', 'NOT_CONFIGURED'))
);

-- Status transitions (healthy <-> failed <-> not configured), for history and reports.
CREATE TABLE AIVA_health_check_events (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    component_key  VARCHAR2(64)  NOT NULL,
    old_status     VARCHAR2(16),
    new_status     VARCHAR2(16)  NOT NULL,
    reason         VARCHAR2(4000),
    created_at     TIMESTAMP(6)  DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    CONSTRAINT pk_aiva_health_check_events PRIMARY KEY (id)
);

CREATE INDEX idx_aiva_health_evt_time ON AIVA_health_check_events (created_at);
