-- Document intelligence — migration V002 (Phase 2: SharePoint / OneDrive sync -> CRM store)
--
-- Creates NEW, isolated tables only. No existing table is altered, and there are no
-- foreign keys to existing tables; the foreign keys below only link these new tables.
-- Requires V001 (the AIVA_di_schema_version ledger).
-- Apply with:   python -m backend.doc_intel.migrate apply --version 002 --confirm-schema <SCHEMA> --yes
-- Roll back:    python -m backend.doc_intel.migrate rollback --version 002 --confirm-schema <SCHEMA> --yes
-- All timestamps are UTC. Credentials are stored ENCRYPTED (Fernet) by the application.

-- A SharePoint / OneDrive folder to sync, with its Microsoft Graph app credentials and schedule.
CREATE TABLE AIVA_crm_sources (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR2(512)  NOT NULL,
    account_id          NUMBER,
    provider            VARCHAR2(32)   DEFAULT 'microsoft_graph' NOT NULL,
    tenant_id_enc       VARCHAR2(1024),
    client_id_enc       VARCHAR2(1024),
    client_secret_enc   VARCHAR2(2048),
    client_secret_hint  VARCHAR2(16),
    secret_updated_at   TIMESTAMP(6),
    site_url            VARCHAR2(1024),
    drive_name          VARCHAR2(512),
    folder_path         VARCHAR2(2000),
    recursive           NUMBER(1)      DEFAULT 1 NOT NULL,
    file_extensions     VARCHAR2(256)  DEFAULT '.pdf,.docx' NOT NULL,
    use_intelligence    NUMBER(1)      DEFAULT 0 NOT NULL,
    resolved_site_id    VARCHAR2(512),
    resolved_drive_id   VARCHAR2(512),
    resolved_folder_id  VARCHAR2(512),
    sync_enabled        NUMBER(1)      DEFAULT 0 NOT NULL,
    sync_interval_days  NUMBER         DEFAULT 14 NOT NULL,
    sync_hour           NUMBER         DEFAULT 2 NOT NULL,
    next_sync_at        TIMESTAMP(6),
    last_sync_at        TIMESTAMP(6),
    last_sync_status    VARCHAR2(16),
    last_sync_error     VARCHAR2(4000),
    last_success_at     TIMESTAMP(6),
    status              VARCHAR2(16)   DEFAULT 'ACTIVE' NOT NULL,
    created_by          NUMBER,
    updated_by          NUMBER,
    created_at          TIMESTAMP(6)   DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    updated_at          TIMESTAMP(6)   DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    CONSTRAINT pk_aiva_crm_sources PRIMARY KEY (id),
    CONSTRAINT ck_aiva_crm_src_status CHECK (status IN ('ACTIVE', 'DISABLED', 'DELETED')),
    CONSTRAINT ck_aiva_crm_src_flags CHECK (recursive IN (0, 1) AND use_intelligence IN (0, 1) AND sync_enabled IN (0, 1)),
    CONSTRAINT ck_aiva_crm_src_schedule CHECK (sync_interval_days BETWEEN 1 AND 365 AND sync_hour BETWEEN 0 AND 23)
);

-- One sync run ("Sync now" or scheduled). QUEUED rows are the sync work queue.
CREATE TABLE AIVA_crm_sync_runs (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY,
    source_id        NUMBER         NOT NULL,
    trigger_type     VARCHAR2(16)   NOT NULL,
    triggered_by     NUMBER,
    status           VARCHAR2(16)   DEFAULT 'QUEUED' NOT NULL,
    worker_id        VARCHAR2(128),
    files_seen       NUMBER         DEFAULT 0 NOT NULL,
    files_new        NUMBER         DEFAULT 0 NOT NULL,
    files_changed    NUMBER         DEFAULT 0 NOT NULL,
    files_deleted    NUMBER         DEFAULT 0 NOT NULL,
    files_unchanged  NUMBER         DEFAULT 0 NOT NULL,
    files_failed     NUMBER         DEFAULT 0 NOT NULL,
    error_message    VARCHAR2(4000),
    details_json     CLOB,
    created_at       TIMESTAMP(6)   DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    started_at       TIMESTAMP(6),
    finished_at      TIMESTAMP(6),
    updated_at       TIMESTAMP(6)   DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    CONSTRAINT pk_aiva_crm_sync_runs PRIMARY KEY (id),
    CONSTRAINT fk_aiva_crm_run_source FOREIGN KEY (source_id) REFERENCES AIVA_crm_sources (id) ON DELETE CASCADE,
    CONSTRAINT ck_aiva_crm_run_trigger CHECK (trigger_type IN ('SCHEDULED', 'MANUAL')),
    CONSTRAINT ck_aiva_crm_run_status CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED'))
);

CREATE INDEX idx_aiva_crm_runs_source ON AIVA_crm_sync_runs (source_id, created_at);

CREATE INDEX idx_aiva_crm_runs_status ON AIVA_crm_sync_runs (status, created_at);

-- At most one QUEUED or RUNNING sync per source (a double "Sync now" cannot start two runs).
CREATE UNIQUE INDEX uq_aiva_crm_run_active ON AIVA_crm_sync_runs (
    CASE WHEN status IN ('QUEUED', 'RUNNING') THEN source_id END
);

-- Files seen in a source's folder, with the per-file pipeline stages.
CREATE TABLE AIVA_crm_source_files (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    source_id            NUMBER         NOT NULL,
    drive_id             VARCHAR2(512)  NOT NULL,
    item_id              VARCHAR2(512)  NOT NULL,
    name                 VARCHAR2(1024),
    path                 VARCHAR2(4000),
    web_url              VARCHAR2(4000),
    etag                 VARCHAR2(512),
    ctag                 VARCHAR2(512),
    quick_xor_hash       VARCHAR2(128),
    content_sha256       VARCHAR2(64),
    size_bytes           NUMBER,
    modified_at          TIMESTAMP(6),
    state                VARCHAR2(16)   DEFAULT 'ACTIVE'  NOT NULL,
    status               VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    download_status      VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    extraction_status    VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    intelligence_status  VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    entities_status      VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    persist_status       VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    failed_stage         VARCHAR2(16),
    error_message        VARCHAR2(4000),
    warnings_json        CLOB,
    result_json          CLOB,
    stage_details        CLOB,
    entity_count         NUMBER,
    is_valid             NUMBER(1),
    attempts             NUMBER         DEFAULT 0 NOT NULL,
    last_run_id          NUMBER,
    first_seen_at        TIMESTAMP(6)   DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    last_seen_at         TIMESTAMP(6),
    processed_at         TIMESTAMP(6),
    deleted_at           TIMESTAMP(6),
    updated_at           TIMESTAMP(6)   DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    CONSTRAINT pk_aiva_crm_source_files PRIMARY KEY (id),
    CONSTRAINT fk_aiva_crm_file_source FOREIGN KEY (source_id) REFERENCES AIVA_crm_sources (id) ON DELETE CASCADE,
    CONSTRAINT uq_aiva_crm_file_item UNIQUE (source_id, drive_id, item_id),
    CONSTRAINT ck_aiva_crm_file_state CHECK (state IN ('ACTIVE', 'DELETED')),
    CONSTRAINT ck_aiva_crm_file_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED')),
    CONSTRAINT ck_aiva_crm_file_stages CHECK (
        download_status     IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED') AND
        extraction_status   IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED') AND
        intelligence_status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED') AND
        entities_status     IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED') AND
        persist_status      IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED')
    )
);

CREATE INDEX idx_aiva_crm_files_status ON AIVA_crm_source_files (source_id, state, status);

-- The internal CRM store: entities extracted from source files, with provenance.
CREATE TABLE AIVA_crm_entities (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    source_id       NUMBER         NOT NULL,
    source_file_id  NUMBER         NOT NULL,
    account_id      NUMBER,
    entity_type     VARCHAR2(64)   NOT NULL,
    display_value   VARCHAR2(1024),
    match_key       VARCHAR2(1024),
    confidence      NUMBER,
    is_valid        NUMBER(1),
    fields_json     CLOB,
    issues_json     CLOB,
    status          VARCHAR2(16)   DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP(6)   DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    updated_at      TIMESTAMP(6)   DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    withdrawn_at    TIMESTAMP(6),
    CONSTRAINT pk_aiva_crm_entities PRIMARY KEY (id),
    CONSTRAINT fk_aiva_crm_ent_file FOREIGN KEY (source_file_id) REFERENCES AIVA_crm_source_files (id) ON DELETE CASCADE,
    CONSTRAINT ck_aiva_crm_ent_status CHECK (status IN ('ACTIVE', 'WITHDRAWN'))
);

CREATE INDEX idx_aiva_crm_ent_file ON AIVA_crm_entities (source_file_id, status);

CREATE INDEX idx_aiva_crm_ent_source ON AIVA_crm_entities (source_id, entity_type, status);
